_wandb:
    value:
        cli_version: 0.27.1
        e:
            orsnp2jvs361aybwe013or3zxuwbk5vt:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    macModel: Mac16,12
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "5368709120"
                args:
                    - --load
                    - unet_carvana_scale0.5_epoch2.pth
                    - --scale
                    - "0.5"
                    - --epochs
                    - "10"
                    - --batch-size
                    - "1"
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "211723689984"
                email: qbix666@gmail.com
                executable: /Users/jakubmatkowski/Dokumenty/PW_repos/ADOM/.venv/bin/python
                git:
                    commit: ed01c353ce5c8074315e28f6ba73fa01e33ce7a0
                    remote: https://github.com/trawiasz-skuter/ADOM.git
                host: macbook-air-jakub-2.home
                memory:
                    total: "17179869184"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/jakubmatkowski/Dokumenty/PW_repos/ADOM/train.py
                python: CPython 3.10.19
                root: /Users/jakubmatkowski/Dokumenty/PW_repos/ADOM
                startedAt: "2026-06-04T11:05:03.993366Z"
                writerId: orsnp2jvs361aybwe013or3zxuwbk5vt
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
                - 100
            "2":
                - 1
                - 41
                - 100
            "4": 3.10.19
            "5": 0.27.1
            "12": 0.27.1
            "13": darwin-arm64
amp:
    value: false
batch_size:
    value: 1
epochs:
    value: 10
img_scale:
    value: 0.5
learning_rate:
    value: 1e-05
save_checkpoint:
    value: true
val_percent:
    value: 0.1
