_wandb:
    value:
        cli_version: 0.27.1
        e:
            rhj3zviv6l4x4kjevxjg5bax2kbw5uir:
                apple:
                    ecpuCores: 6
                    gpuCores: 8
                    macModel: Mac16,12
                    memoryGb: 16
                    name: Apple M4
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "4294967296"
                args:
                    - --img-dir
                    - Dataset/Breast-Ultrasound-Processed/images
                    - --mask-dir
                    - Dataset/Breast-Ultrasound-Processed/masks
                    - --size
                    - "128"
                    - --epochs
                    - "10"
                    - --batch-size
                    - "1"
                    - --classes
                    - "1"
                    - --loss
                    - dice
                codePath: train.py
                codePathLocal: train.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "245107195904"
                        used: "208074596352"
                email: qbix666@gmail.com
                executable: /Users/jakubmatkowski/Dokumenty/PW_repos/ADOM/.venv/bin/python
                git:
                    commit: ed01c353ce5c8074315e28f6ba73fa01e33ce7a0
                    remote: https://github.com/trawiasz-skuter/ADOM.git
                host: macbook-air-jakub-2.home
                memory:
                    total: "17179869184"
                os: macOS-26.3.1-arm64-arm-64bit
                program: /Users/jakubmatkowski/Dokumenty/PW_repos/ADOM/train.py
                python: CPython 3.10.19
                root: /Users/jakubmatkowski/Dokumenty/PW_repos/ADOM
                startedAt: "2026-06-05T13:00:57.114659Z"
                writerId: rhj3zviv6l4x4kjevxjg5bax2kbw5uir
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 41
                - 49
                - 63
                - 74
                - 100
            "2":
                - 1
                - 41
                - 49
                - 63
                - 74
                - 100
            "4": 3.10.19
            "5": 0.27.1
            "12": 0.27.1
            "13": darwin-arm64
amp:
    value: false
augment:
    value: false
batch_size:
    value: 1
epochs:
    value: 10
learning_rate:
    value: 1e-05
loss_type:
    value: dice
save_checkpoint:
    value: true
target_size:
    value: 128
val_percent:
    value: 0.1
